#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

// #include "log.h"

#include <stdio.h>
#include <stdlib.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	//fprintf(stderr, "TODO: longest prefix match for the packet.\n");
	//return NULL;
	u32 longest_mask = 0;
	rt_entry_t *rt;
	rt_entry_t *rt_longest = NULL; // 最长前缀掩码对应的表项
	
	list_for_each_entry(rt, &rtable, list) 
	{
		if ((rt->mask > longest_mask) && ((rt->dest & rt->mask) == (dst & rt->mask))) 
		{
			longest_mask = rt->mask;
			rt_longest = rt;
		}
	}
	return rt_longest;
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	//fprintf(stderr, "TODO: send ip packet.\n");
	struct iphdr *iphdr = packet_to_ip_hdr(packet);
	u32 dest_ip = ntohl(iphdr->daddr);
	rt_entry_t *rt_dest = longest_prefix_match(dest_ip);

	if (rt_dest->gw)
		iface_send_packet_by_arp(rt_dest->iface, rt_dest->gw, packet, len);
	else
		iface_send_packet(rt_dest->iface, packet, len);
}
